// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD-nRjSUmE2bQoD9E1Z-lz_x-NDEwRqug',
    appId: '1:295261572139:web:9ddabbcb8fecdfa97aae6e',
    messagingSenderId: '295261572139',
    projectId: 'homecare-f3078',
    authDomain: 'homecare-f3078.firebaseapp.com',
    storageBucket: 'homecare-f3078.firebasestorage.app',
    measurementId: 'G-NLZ84Q57BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3aQZlZd00VR3Q6OJ_q9T2VrhYUQmb4I',
    appId: '1:295261572139:android:135a69ee4121f1787aae6e',
    messagingSenderId: '295261572139',
    projectId: 'homecare-f3078',
    storageBucket: 'homecare-f3078.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkK4JjwTOveuPkCquJRmp4nJKb6fVjuqQ',
    appId: '1:295261572139:ios:6e8cdedf58baacb07aae6e',
    messagingSenderId: '295261572139',
    projectId: 'homecare-f3078',
    storageBucket: 'homecare-f3078.firebasestorage.app',
    iosBundleId: 'com.example.homecare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkK4JjwTOveuPkCquJRmp4nJKb6fVjuqQ',
    appId: '1:295261572139:ios:6e8cdedf58baacb07aae6e',
    messagingSenderId: '295261572139',
    projectId: 'homecare-f3078',
    storageBucket: 'homecare-f3078.firebasestorage.app',
    iosBundleId: 'com.example.homecare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD-nRjSUmE2bQoD9E1Z-lz_x-NDEwRqug',
    appId: '1:295261572139:web:d9a062ef3763aac57aae6e',
    messagingSenderId: '295261572139',
    projectId: 'homecare-f3078',
    authDomain: 'homecare-f3078.firebaseapp.com',
    storageBucket: 'homecare-f3078.firebasestorage.app',
    measurementId: 'G-506XR2XMPK',
  );
}
